### ISSUE TITLE
Getting error when trying to add an item to a list

### ISSUE THREAD

**Issue by Eldorian** [stoiveyp/Alexa.NET.ListManagement#3]
I'm trying to do this:

`await client.AddItem(listId, "adding an item", "active");`

Where listId is a string that I grabbed earlier. 

I get the following error:

One or more errors occurred. (String was not recognized as a valid DateTime.): AggregateException
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

at System.DateTime.ParseExact(String s, String format, IFormatProvider provider)
at Alexa.NET.ListManagement.Requests.SkillItemDateConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
at Alexa.NET.ListManagementClient.<AddItem>d__11.MoveNext()

**Comment by Eldorian** [comment]
Following up on this, but today I noticed that Alexa actually put the item in the list I told it too. Just in the logs I get that error I presented and also Alexa responds that there is an error.

**Comment by Eldorian** [comment]
I ended up getting around Alexa returning back an error message by just wrapping the AddItem in a try/catch - it still adds it for some reason but now won't return an error message. Weird work around.
