### ISSUE TITLE
GetList throws an error about string not recognized as a valid DateTime

### ISSUE THREAD

**Issue by Eldorian** [stoiveyp/Alexa.NET.ListManagement#4]
I have a list I created - all that is in the list is "Thing" and "Something" as the items.

I can pull the list meta data and get the list id just fine.

However, when I try:

await client.GetList(listId, "active")

I get the following error

One or more errors occurred. (String was not recognized as a valid DateTime.): AggregateException
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

at System.DateTime.ParseExact(String s, String format, IFormatProvider provider)
at Alexa.NET.ListManagement.Requests.SkillItemDateConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
at Alexa.NET.ListManagementClient.<GetList>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

This seems similar to issue #3 I was having.

**Comment by stoiveyp** [comment]
@Eldorian - Apologies for not noticing your issues until today. There seems to have been an oversight on my part on maintaining a watch on this repo - I do try and reply promptly.

v1.0.30 (PR #8) should now fix both this issue and #3 - I tweaked the converter for the date time to fix the issue, as default DateTime parsing caused other tests to fail. NuGet is currently validating this new package so it should be live shortly

Please let me know if this update does fix the problem. I've also added a really quick list management sample with some basic logging into https://github.com/stoiveyp/Alexa.NET.Samples

**Comment by Eldorian** [comment]
Haven't seen it come across nuget yet but I cloned the repo and tested it out, and yeah, it fixes the issues I was having. Thanks!
